import {defineArrayMember, defineField, defineType} from 'sanity'
import {BillIcon} from '@sanity/icons/Bill'

export const orderStatuses = [
  {title: 'Pending', value: 'pending'},
  {title: 'Confirmed', value: 'confirmed'},
  {title: 'Processing', value: 'processing'},
  {title: 'Shipped', value: 'shipped'},
  {title: 'Delivered', value: 'delivered'},
  {title: 'Cancelled', value: 'cancelled'},
  {title: 'Returned', value: 'returned'},
] as const

export const order = defineType({
  name: 'order',
  title: 'Order',
  type: 'document',
  icon: BillIcon,
  groups: [
    {name: 'summary', title: 'Summary', default: true},
    {name: 'items', title: 'Items'},
    {name: 'delivery', title: 'Delivery'},
    {name: 'payment', title: 'Payment'},
    {name: 'internal', title: 'Internal'},
  ],
  fields: [
    defineField({
      name: 'orderNumber',
      title: 'Order number',
      type: 'string',
      group: 'summary',
      readOnly: true,
      description: 'Generated by the storefront. Human-readable, safe to share with the shopper.',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      group: 'summary',
      options: {list: [...orderStatuses], layout: 'radio'},
      initialValue: 'pending',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'placedAt',
      title: 'Placed at',
      type: 'datetime',
      group: 'summary',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'customer',
      title: 'Customer',
      type: 'reference',
      group: 'summary',
      to: [{type: 'customer'}],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'items',
      title: 'Items',
      type: 'array',
      group: 'items',
      of: [defineArrayMember({type: 'orderLineItem'})],
      validation: (rule) => rule.required().min(1).error('An order needs at least one item.'),
    }),
    defineField({
      name: 'currency',
      title: 'Currency',
      type: 'string',
      group: 'items',
      initialValue: 'BDT',
      readOnly: true,
    }),
    defineField({
      name: 'subtotal',
      title: 'Subtotal',
      type: 'number',
      group: 'items',
      validation: (rule) => rule.required().min(0),
    }),
    defineField({
      name: 'shippingFee',
      title: 'Delivery fee',
      type: 'number',
      group: 'items',
      initialValue: 0,
      validation: (rule) => rule.min(0),
    }),
    defineField({
      name: 'discount',
      title: 'Discount',
      type: 'number',
      group: 'items',
      initialValue: 0,
      validation: (rule) => rule.min(0),
    }),
    defineField({
      name: 'total',
      title: 'Total',
      type: 'number',
      group: 'items',
      validation: (rule) =>
        rule
          .required()
          .min(0)
          .custom((total, context) => {
            const doc = context.document as
              | {subtotal?: number; shippingFee?: number; discount?: number}
              | undefined
            if (!doc || typeof total !== 'number' || typeof doc.subtotal !== 'number') return true
            const expected = doc.subtotal + (doc.shippingFee ?? 0) - (doc.discount ?? 0)
            return Math.abs(expected - total) < 0.01
              ? true
              : `Total should be ${expected.toLocaleString()} (subtotal + delivery − discount).`
          }),
    }),
    defineField({
      name: 'shippingAddress',
      title: 'Delivery address',
      type: 'address',
      group: 'delivery',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'courier',
      title: 'Courier',
      type: 'string',
      group: 'delivery',
      description: 'For example Pathao, Steadfast or RedX.',
    }),
    defineField({
      name: 'trackingNumber',
      title: 'Tracking number',
      type: 'string',
      group: 'delivery',
    }),
    defineField({
      name: 'customerNote',
      title: 'Note from customer',
      type: 'text',
      rows: 3,
      group: 'delivery',
      readOnly: true,
    }),
    defineField({
      name: 'payment',
      title: 'Payment',
      type: 'paymentDetails',
      group: 'payment',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'internalNotes',
      title: 'Internal notes',
      type: 'text',
      rows: 4,
      group: 'internal',
    }),
    defineField({
      name: 'source',
      title: 'Source',
      type: 'string',
      group: 'internal',
      readOnly: true,
      options: {
        list: [
          {title: 'Storefront', value: 'storefront'},
          {title: 'Entered by staff', value: 'manual'},
        ],
      },
      initialValue: 'manual',
    }),
  ],
  orderings: [
    {title: 'Newest first', name: 'placedAtDesc', by: [{field: 'placedAt', direction: 'desc'}]},
    {title: 'Highest value', name: 'totalDesc', by: [{field: 'total', direction: 'desc'}]},
  ],
  preview: {
    select: {
      orderNumber: 'orderNumber',
      status: 'status',
      total: 'total',
      currency: 'currency',
      customerName: 'customer.name',
      paymentStatus: 'payment.status',
    },
    prepare({orderNumber, status, total, currency, customerName, paymentStatus}) {
      const statusLabel = orderStatuses.find((entry) => entry.value === status)?.title ?? status
      const amount = typeof total === 'number' ? `${currency ?? ''} ${total.toLocaleString()}`.trim() : null
      return {
        title: [orderNumber, customerName].filter(Boolean).join(' · '),
        subtitle: [statusLabel, amount, paymentStatus === 'paid' ? 'Paid' : paymentStatus]
          .filter(Boolean)
          .join(' · '),
      }
    },
  },
})
