/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ProductVariant = {
  _type: "productVariant";
  size?: "XS" | "S" | "M" | "L" | "XL" | "XXL" | "3XL" | "ONE";
  colour?: string;
  colourHex?: string;
  sku?: string;
  price?: number;
  stock?: number;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  status?: "draft" | "active" | "paused";
  summary?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  startingPrice?: number;
  minimumQuantity?: number;
  turnaroundDays?: number;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type Collection = {
  _id: string;
  _type: "collection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  products?: Array<
    {
      _key: string;
    } & ProductReference
  >;
  seo?: Seo;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  parent?: CategoryReference;
  seo?: Seo;
};

export type BrandReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "brand";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  productType?:
    "tshirt" | "dropShoulder" | "footballJersey" | "cricketJersey" | "other";
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  excerpt?: string;
  description?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  featured?: boolean;
  fabric?: string;
  gsm?: number;
  fit?: "regular" | "oversized" | "dropShoulder" | "slim" | "player";
  audience?: "unisex" | "men" | "women" | "kids";
  careInstructions?: Array<string>;
  sizeChart?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  team?: string;
  season?: string;
  kitType?: "home" | "away" | "third" | "goalkeeper" | "training" | "retro";
  customisable?: boolean;
  status?: "draft" | "active" | "archived";
  price?: number;
  compareAtPrice?: number;
  sku?: string;
  stock?: number;
  variants?: Array<
    {
      _key: string;
    } & ProductVariant
  >;
  brand?: BrandReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  seo?: Seo;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  description?: string;
  website?: string;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  storeName?: string;
  tagline?: string;
  heroHeading?: string;
  heroText?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  announcement?: {
    enabled?: boolean;
    text?: string;
    href?: string;
  };
  contactEmail?: string;
  contactPhone?: string;
  whatsapp?: string;
  social?: {
    facebook?: string;
    instagram?: string;
    tiktok?: string;
    youtube?: string;
  };
  currency?: string;
  shipping?: {
    insideDhakaFee?: number;
    outsideDhakaFee?: number;
    freeShippingThreshold?: number;
  };
  enabledPaymentMethods?: Array<string>;
  paymentInstructions?: {
    bkashNumber?: string;
    nagadNumber?: string;
    bankDetails?: string;
  };
  jerseyCustomisationFee?: number;
  defaultSeo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Seo
  | ProductVariant
  | Service
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | ProductReference
  | Collection
  | CategoryReference
  | Category
  | BrandReference
  | Product
  | Brand
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/src/infrastructure/sanity/queries.ts
// Variable: PURCHASABLE_PRODUCTS_QUERY
// Query: *[_type == "product" && status == "active" && defined(slug.current)]{      _id,  name,  "slug": slug.current,  excerpt,  price,  compareAtPrice,  stock,  "primaryImage": images[0]{  "assetId": asset._ref,  alt,  hotspot},  "brand": brand->{name, "slug": slug.current},  "variants": variants[]{stock}  }
export type PURCHASABLE_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  excerpt: string | null;
  price: number | null;
  compareAtPrice: number | null;
  stock: number | null;
  primaryImage: {
    assetId: string | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  brand: {
    name: string | null;
    slug: string | null;
  } | null;
  variants: Array<{
    stock: number | null;
  }> | null;
}>;

// Source: ../web/src/infrastructure/sanity/queries.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    excerpt,    description,    status,    price,    compareAtPrice,    sku,    stock,    "images": images[]{  "assetId": asset._ref,  alt,  hotspot},    "brand": brand->{name, "slug": slug.current},    "categories": categories[]->{_id, title, "slug": slug.current},    "variants": variants[]{      _key,      title,      sku,      price,      stock,      "options": options[]{name, value}    },    "seo": seo{      title,      description,      "shareImage": image{  "assetId": asset._ref,  alt,  hotspot}    }  }
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  excerpt: string | null;
  description: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  > | null;
  status: "active" | "archived" | "draft" | null;
  price: number | null;
  compareAtPrice: number | null;
  sku: string | null;
  stock: number | null;
  images: Array<{
    assetId: string | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
  }> | null;
  brand: {
    name: string | null;
    slug: string | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  variants: Array<{
    _key: string;
    title: null;
    sku: string | null;
    price: number | null;
    stock: number | null;
    options: null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    shareImage: {
      assetId: string | null;
      alt: null;
      hotspot: SanityImageHotspot | null;
    } | null;
  } | null;
} | null;

// Source: ../web/src/infrastructure/sanity/queries.ts
// Variable: PURCHASABLE_PRODUCT_SLUGS_QUERY
// Query: *[_type == "product" && status == "active" && defined(slug.current)].slug.current
export type PURCHASABLE_PRODUCT_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../web/src/infrastructure/sanity/queries.ts
// Variable: PRODUCT_SEO_BY_SLUG_QUERY
// Query: *[_type == "product" && slug.current == $slug][0]{    name,    excerpt,    "seo": seo{      title,      description,      "shareImage": image{  "assetId": asset._ref,  alt,  hotspot}    }  }
export type PRODUCT_SEO_BY_SLUG_QUERY_RESULT = {
  name: string | null;
  excerpt: string | null;
  seo: {
    title: string | null;
    description: string | null;
    shareImage: {
      assetId: string | null;
      alt: null;
      hotspot: SanityImageHotspot | null;
    } | null;
  } | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "product" && status == "active" && defined(slug.current)]{\n    \n  _id,\n  name,\n  "slug": slug.current,\n  excerpt,\n  price,\n  compareAtPrice,\n  stock,\n  "primaryImage": images[0]{\n  "assetId": asset._ref,\n  alt,\n  hotspot\n},\n  "brand": brand->{name, "slug": slug.current},\n  "variants": variants[]{stock}\n\n  }\n': PURCHASABLE_PRODUCTS_QUERY_RESULT;
    '\n  *[_type == "product" && slug.current == $slug][0]{\n    _id,\n    name,\n    "slug": slug.current,\n    excerpt,\n    description,\n    status,\n    price,\n    compareAtPrice,\n    sku,\n    stock,\n    "images": images[]{\n  "assetId": asset._ref,\n  alt,\n  hotspot\n},\n    "brand": brand->{name, "slug": slug.current},\n    "categories": categories[]->{_id, title, "slug": slug.current},\n    "variants": variants[]{\n      _key,\n      title,\n      sku,\n      price,\n      stock,\n      "options": options[]{name, value}\n    },\n    "seo": seo{\n      title,\n      description,\n      "shareImage": image{\n  "assetId": asset._ref,\n  alt,\n  hotspot\n}\n    }\n  }\n': PRODUCT_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "product" && status == "active" && defined(slug.current)].slug.current\n': PURCHASABLE_PRODUCT_SLUGS_QUERY_RESULT;
    '\n  *[_type == "product" && slug.current == $slug][0]{\n    name,\n    excerpt,\n    "seo": seo{\n      title,\n      description,\n      "shareImage": image{\n  "assetId": asset._ref,\n  alt,\n  hotspot\n}\n    }\n  }\n': PRODUCT_SEO_BY_SLUG_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
